language: objective-c
osx_image: xcode7.2

script:
  - xcodebuild clean build test -workspace BioSwift.xcworkspace -scheme BioSwift -destination 'platform=OS X,arch=x86_64' GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

after_success:
 - bash <(curl -s https://codecov.io/bash)
