language: objective-c
osx_image: xcode7.2

script:
  - xcodebuild clean build test -workspace BioSwift.xcworkspace -scheme BioSwift -sdk 'macosx10.11' -destination 'platform=OS X,arch=x86_64' | xcpretty

after_success:
 - bash <(curl -s https://codecov.io/bash)
